environment:
  matrix:
    # does not work with sw now
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      #platform: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: Win32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: Win64
    #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      #platform: Win64

cache:
  - c:/Users/appveyor/.sw -> appveyor.yml

configuration:
  - Release

# for curl
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

before_build:
  - curl -fsS -L -o sw.zip https://github.com/SoftwareNetwork/binaries/raw/master/sw-master-windows-client.zip
  - 7z x sw.zip
  - set PATH=%PATH%;%cd%

build_script:
  - sw -version
  - sw -show-output -platform %platform% build

after_build:
  - 7z a leptonica.zip %APPVEYOR_BUILD_FOLDER%\.sw\out\**\*.exe %APPVEYOR_BUILD_FOLDER%\.sw\out\**\*.dll
  #- 7z a leptonica.zip %APPVEYOR_BUILD_FOLDER%\.sw\Windows_*_Shared_Release_MSVC_*\*.exe %APPVEYOR_BUILD_FOLDER%\.sw\Windows_*_Shared_Release_MSVC_*\*.dll

artifacts:
  - path: leptonica.zip
    name: leptonica-$(APPVEYOR_BUILD_VERSION)
    
